services:
  app:
    build:
      context: .
    ports:
      - 5910:5910
    volumes:
      - swayvnc-wayvnc-certs:/certs
    environment:
      - RENDER_GROUP_GID=107 # replace with GID of the group which owns the /dev/dri/renderD128 device
      - SWAY_RESOLUTION=1920x1080
      - WAYVNC_PORT=5910
      - WAYVNC_ENABLE_AUTH=true
      - WAYVNC_USERNAME=wayvnc
      - WAYVNC_PASSWORD=wayvnc
    # privileged: true
    cap_add:
      - SYS_ADMIN

volumes:
  swayvnc-wayvnc-certs:
